version: '3.8'

services:
  db:
    image: postgres:13.2
    ports:
      - 58101:5432
    environment:
      - POSTGRES_USER=quokka_editor_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quokka_editor_db

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    command: python -m quokka_editor_back run --debug
    environment:
      - DEBUG=true
      - DATABASE_DSN=postgres://quokka_editor_user:password@db:5432/quokka_editor_db
      - SECRET_KEY=${SECRET_KEY:?Provide this variable for the app to work}
    volumes:
      - ./src/quokka_editor_back:/app/src/quokka_editor_back
    ports:
      - "8100:8080"
    depends_on:
      - db